// Catálogo de materiales de referencia (densidad y métrica de cómputo) para
// que arquitectos/civiles elijan materiales al crear o editar una tarea.
// Generado a partir de una lista de referencia preparada por el usuario.
// No se ejecuta solo: correr con `npm run seed:materials` contra la
// DATABASE_URL de destino. Es seguro correrlo varias veces (upsert por
// categoría + nombre); no borra materiales ya usados por tareas existentes.

import 'dotenv/config';
import { pool, prisma } from '../src/lib/prisma';

type MaterialSeed = { category: string; name: string; density: number; metricLabel: string };

const MATERIALS: MaterialSeed[] = [
  { category: "Concreto", name: "Concreto normal (peso normal)", density: 2400, metricLabel: "Volumen (m³)" },
  { category: "Concreto", name: "Concreto liviano estructural", density: 1850, metricLabel: "Volumen (m³)" },
  { category: "Concreto", name: "Concreto liviano no estructural (aislante)", density: 1000, metricLabel: "Volumen (m³)" },
  { category: "Concreto", name: "Concreto de alta resistencia", density: 2450, metricLabel: "Volumen (m³)" },
  { category: "Concreto", name: "Concreto celular / aireado (AAC in situ)", density: 600, metricLabel: "Volumen (m³)" },
  { category: "Concreto", name: "Concreto permeable / poroso", density: 1900, metricLabel: "Volumen (m³)" },
  { category: "Concreto", name: "Concreto reforzado con fibra", density: 2450, metricLabel: "Volumen (m³)" },
  { category: "Concreto", name: "Concreto ciclópeo", density: 2300, metricLabel: "Volumen (m³)" },
  { category: "Concreto", name: "Mortero de cemento", density: 2100, metricLabel: "Volumen (m³) / Área (m²)" },
  { category: "Concreto", name: "Mortero de cal", density: 1600, metricLabel: "Volumen (m³) / Área (m²)" },
  { category: "Concreto", name: "Concreto asfáltico (pavimento)", density: 2400, metricLabel: "Volumen (m³) / Área (m²)" },
  { category: "Concreto", name: "Concreto autocompactante (SCC)", density: 2400, metricLabel: "Volumen (m³)" },
  { category: "Concreto", name: "Concreto proyectado (shotcrete)", density: 2400, metricLabel: "Volumen (m³)" },
  { category: "Concreto", name: "Adoquín de concreto (pavimento)", density: 2300, metricLabel: "Área (m²) / unidad" },
  { category: "Concreto", name: "Mortero autonivelante para piso", density: 2000, metricLabel: "Área (m²) / Volumen (m³)" },
  { category: "Concreto", name: "Concreto con áridos reciclados", density: 2300, metricLabel: "Volumen (m³)" },
  { category: "Concreto", name: "Concreto translúcido (con fibra óptica)", density: 2350, metricLabel: "Volumen (m³)" },
  { category: "Concreto", name: "Concreto de ultra alto desempeño (UHPC)", density: 2500, metricLabel: "Volumen (m³)" },
  { category: "Concreto", name: "Concreto con perlita (liviano térmico)", density: 900, metricLabel: "Volumen (m³)" },
  { category: "Concreto", name: "Concreto con arcilla expandida (LECA)", density: 1400, metricLabel: "Volumen (m³)" },
  { category: "Concreto", name: "Grout de nivelación estructural", density: 2200, metricLabel: "Volumen (m³)" },
  { category: "Concreto", name: "Concreto lanzado vía seca", density: 2350, metricLabel: "Volumen (m³)" },
  { category: "Concreto", name: "Concreto para pisos industriales (alta abrasión)", density: 2450, metricLabel: "Volumen (m³)" },
  { category: "Concreto", name: "Hormigón compactado con rodillo (RCC)", density: 2400, metricLabel: "Volumen (m³)" },
  { category: "Concreto", name: "Mortero de reparación estructural", density: 2100, metricLabel: "Volumen (m³)" },
  { category: "Acero y hierro", name: "Acero estructural (A36 / A992)", density: 7850, metricLabel: "Peso (kg / ton)" },
  { category: "Acero y hierro", name: "Acero de refuerzo (varilla corrugada)", density: 7850, metricLabel: "Peso (kg / ton)" },
  { category: "Acero y hierro", name: "Acero inoxidable 304", density: 8000, metricLabel: "Peso (kg / ton)" },
  { category: "Acero y hierro", name: "Acero inoxidable 316", density: 8000, metricLabel: "Peso (kg / ton)" },
  { category: "Acero y hierro", name: "Acero galvanizado", density: 7850, metricLabel: "Peso (kg / ton)" },
  { category: "Acero y hierro", name: "Hierro fundido gris", density: 7200, metricLabel: "Peso (kg / ton)" },
  { category: "Acero y hierro", name: "Hierro fundido dúctil", density: 7100, metricLabel: "Peso (kg / ton)" },
  { category: "Acero y hierro", name: "Acero para cables / tensores", density: 7850, metricLabel: "Peso (kg / ton) / Longitud (m)" },
  { category: "Acero y hierro", name: "Acero Corten (weathering steel)", density: 7850, metricLabel: "Peso (kg / ton)" },
  { category: "Acero y hierro", name: "Acero conformado en frío (steel stud)", density: 7850, metricLabel: "Peso (kg) / Longitud (m)" },
  { category: "Acero y hierro", name: "Acero de pretensado", density: 7850, metricLabel: "Peso (kg) / Longitud (m)" },
  { category: "Acero y hierro", name: "Perfil laminado IPN / HEB / UPN", density: 7850, metricLabel: "Peso (kg) / Longitud (m)" },
  { category: "Acero y hierro", name: "Perno estructural de alta resistencia (A325)", density: 7850, metricLabel: "Peso (kg) / unidad" },
  { category: "Acero y hierro", name: "Placa de anclaje de acero", density: 7850, metricLabel: "Peso (kg) / unidad" },
  { category: "Acero y hierro", name: "Malla electrosoldada para concreto", density: 7850, metricLabel: "Área (m²)" },
  { category: "Acero y hierro", name: "Malla electrosoldada para pavimento", density: 7850, metricLabel: "Área (m²)" },
  { category: "Acero y hierro", name: "Barra de anclaje roscada", density: 7850, metricLabel: "Peso (kg) / unidad" },
  { category: "Acero y hierro", name: "Acero para tubería (conducción de agua/gas)", density: 7850, metricLabel: "Longitud (m)" },
  { category: "Acero y hierro", name: "Acero al carbono para calderería", density: 7850, metricLabel: "Peso (kg / ton)" },
  { category: "Metales no ferrosos", name: "Aluminio 6061-T6 (estructural)", density: 2700, metricLabel: "Peso (kg) / Longitud (m)" },
  { category: "Metales no ferrosos", name: "Aluminio 6063 (perfiles arquitectónicos)", density: 2700, metricLabel: "Peso (kg) / Longitud (m)" },
  { category: "Metales no ferrosos", name: "Aluminio anodizado (perfil de fachada)", density: 2700, metricLabel: "Peso (kg) / Longitud (m)" },
  { category: "Metales no ferrosos", name: "Cobre", density: 8960, metricLabel: "Peso (kg) / Longitud (m)" },
  { category: "Metales no ferrosos", name: "Cobre patinado (fachada / techo)", density: 8960, metricLabel: "Área (m²)" },
  { category: "Metales no ferrosos", name: "Bronce", density: 8800, metricLabel: "Peso (kg)" },
  { category: "Metales no ferrosos", name: "Latón", density: 8500, metricLabel: "Peso (kg)" },
  { category: "Metales no ferrosos", name: "Latón naval", density: 8400, metricLabel: "Peso (kg)" },
  { category: "Metales no ferrosos", name: "Zinc (planchas / recubrimiento)", density: 7140, metricLabel: "Peso (kg) / Área (m²)" },
  { category: "Metales no ferrosos", name: "Zinc-titanio (fachada / techo)", density: 7200, metricLabel: "Área (m²)" },
  { category: "Metales no ferrosos", name: "Titanio", density: 4500, metricLabel: "Peso (kg)" },
  { category: "Metales no ferrosos", name: "Plomo", density: 11340, metricLabel: "Peso (kg)" },
  { category: "Metales no ferrosos", name: "Níquel", density: 8900, metricLabel: "Peso (kg)" },
  { category: "Metales no ferrosos", name: "Cromo", density: 7150, metricLabel: "Peso (kg)" },
  { category: "Metales no ferrosos", name: "Magnesio", density: 1740, metricLabel: "Peso (kg)" },
  { category: "Metales no ferrosos", name: "Estaño", density: 7280, metricLabel: "Peso (kg)" },
  { category: "Metales no ferrosos", name: "Duraluminio (aleación Al-Cu)", density: 2800, metricLabel: "Peso (kg)" },
  { category: "Metales no ferrosos", name: "Zamak (aleación de zinc)", density: 6600, metricLabel: "Peso (kg)" },
  { category: "Metales no ferrosos", name: "Monel (aleación níquel-cobre)", density: 8800, metricLabel: "Peso (kg)" },
  { category: "Metales no ferrosos", name: "Inconel (aleación níquel-cromo)", density: 8440, metricLabel: "Peso (kg)" },
  { category: "Metales no ferrosos", name: "Acero maraging (alta resistencia)", density: 8100, metricLabel: "Peso (kg)" },
  { category: "Metales no ferrosos", name: "Latón rojo (tombac)", density: 8700, metricLabel: "Peso (kg)" },
  { category: "Metales no ferrosos", name: "Cuproníquel (aleación cobre-níquel)", density: 8900, metricLabel: "Peso (kg)" },
  { category: "Metales no ferrosos", name: "Aleación de aluminio-magnesio (marina)", density: 2660, metricLabel: "Peso (kg)" },
  { category: "Metales no ferrosos", name: "Acero para blindaje balístico", density: 7850, metricLabel: "Peso (kg)" },
  { category: "Madera", name: "Pino (Pinus radiata)", density: 450, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Abeto / spruce", density: 470, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Roble", density: 720, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Haya", density: 720, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Cedro", density: 380, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Caoba", density: 640, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Eucalipto", density: 750, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Balsa", density: 160, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Bambú (estructural)", density: 600, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Madera laminada encolada (Glulam)", density: 500, metricLabel: "Volumen (m³)" },
  { category: "Madera", name: "Contrachapado (plywood)", density: 550, metricLabel: "Área (m²) / unidad" },
  { category: "Madera", name: "OSB (tablero de partículas orientadas)", density: 600, metricLabel: "Área (m²) / unidad" },
  { category: "Madera", name: "MDF (fibra de densidad media)", density: 750, metricLabel: "Área (m²) / unidad" },
  { category: "Madera", name: "Aglomerado (particle board)", density: 650, metricLabel: "Área (m²) / unidad" },
  { category: "Madera", name: "Teca (teak)", density: 650, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Nogal (walnut)", density: 650, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Arce (maple)", density: 700, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Abedul (birch)", density: 670, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Fresno (ash)", density: 690, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Álamo (poplar)", density: 450, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Ciprés (cypress)", density: 500, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Secoya (redwood)", density: 420, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Madera de mango", density: 560, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Caucho (rubberwood)", density: 560, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Madera contralaminada (CLT)", density: 500, metricLabel: "Volumen (m³)" },
  { category: "Madera", name: "Contrachapado marino (marine plywood)", density: 600, metricLabel: "Área (m²) / unidad" },
  { category: "Madera", name: "Tablero de fibra de alta densidad (HDF)", density: 850, metricLabel: "Área (m²) / unidad" },
  { category: "Madera", name: "Tablero de cemento-madera (wood-cement board)", density: 1200, metricLabel: "Área (m²)" },
  { category: "Madera", name: "Ipê (decking)", density: 1050, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Cumaru (decking)", density: 1090, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Garapa (decking)", density: 980, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Massaranduba (decking)", density: 1000, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Jatobá", density: 1050, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Tigerwood / Muiracatiara", density: 950, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Wengué", density: 870, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Zebrano (zebrawood)", density: 790, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Amaranto (purpleheart)", density: 860, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Iroko", density: 660, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Sapelli / sapele", density: 640, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Meranti (rojo claro)", density: 530, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Merbau", density: 840, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Bubinga", density: 890, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Padauk", density: 740, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Ébano", density: 1100, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Palo de rosa (rosewood)", density: 850, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Alerce / larch", density: 590, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Pino Douglas (Douglas fir)", density: 530, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Tsuga / hemlock", density: 500, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Nogal americano (hickory)", density: 830, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Olmo (elm)", density: 560, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Castaño (chestnut)", density: 560, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Aliso (alder)", density: 450, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Tilo (basswood / linden)", density: 420, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Sauce (willow)", density: 450, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Guayacán (lignum vitae)", density: 1280, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Algarrobo (mesquite)", density: 800, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Quebracho", density: 1200, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Lenga", density: 530, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Raulí", density: 480, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Parota / orejero", density: 400, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Encino (roble mexicano)", density: 750, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Madera termotratada (thermowood)", density: 470, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Bambú laminado (decking)", density: 700, metricLabel: "Área (m²)" },
  { category: "Madera", name: "Sen (Mimosa/Samán)", density: 380, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Marupá", density: 400, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Pochote", density: 450, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Cativo", density: 420, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Guanacaste", density: 400, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Roble americano rojo (red oak)", density: 750, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Roble americano blanco (white oak)", density: 770, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Cerezo (cherry)", density: 580, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Sicomoro (sycamore)", density: 590, metricLabel: "Volumen (m³) / unidad" },
  { category: "Madera", name: "Nogal negro (black walnut)", density: 610, metricLabel: "Volumen (m³) / unidad" },
  { category: "Mampostería", name: "Ladrillo cerámico macizo", density: 1850, metricLabel: "Área (m²) / unidad" },
  { category: "Mampostería", name: "Ladrillo cerámico hueco", density: 1200, metricLabel: "Área (m²) / unidad" },
  { category: "Mampostería", name: "Bloque de concreto (CMU) hueco", density: 1200, metricLabel: "Área (m²) / unidad" },
  { category: "Mampostería", name: "Bloque de concreto (CMU) macizo", density: 2100, metricLabel: "Área (m²) / unidad" },
  { category: "Mampostería", name: "Bloque de concreto celular (AAC)", density: 600, metricLabel: "Área (m²) / unidad" },
  { category: "Mampostería", name: "Adobe", density: 1600, metricLabel: "Volumen (m³) / unidad" },
  { category: "Mampostería", name: "Ladrillo refractario", density: 2000, metricLabel: "Área (m²) / unidad" },
  { category: "Mampostería", name: "Tierra apisonada (rammed earth)", density: 1900, metricLabel: "Volumen (m³)" },
  { category: "Mampostería", name: "Bloque de tierra comprimida (CEB)", density: 1700, metricLabel: "Área (m²) / unidad" },
  { category: "Mampostería", name: "Ladrillo de cal y arena (sand-lime brick)", density: 1800, metricLabel: "Área (m²) / unidad" },
  { category: "Mampostería", name: "Ladrillo de ceniza volante (fly ash brick)", density: 1700, metricLabel: "Área (m²) / unidad" },
  { category: "Mampostería", name: "Bloque de vidrio (glass block)", density: 2500, metricLabel: "Área (m²) / unidad" },
  { category: "Mampostería", name: "Bloque sílico-calcáreo", density: 1900, metricLabel: "Área (m²) / unidad" },
  { category: "Mampostería", name: "Bloque de escoria (cinder block)", density: 1500, metricLabel: "Área (m²) / unidad" },
  { category: "Mampostería", name: "Ladrillo pandereta", density: 1100, metricLabel: "Área (m²) / unidad" },
  { category: "Mampostería", name: "Ladrillo King Kong", density: 1750, metricLabel: "Área (m²) / unidad" },
  { category: "Mampostería", name: "Ladrillo tolete / tolete común", density: 1700, metricLabel: "Área (m²) / unidad" },
  { category: "Mampostería", name: "Bloqueta de concreto liviano con perlita", density: 1000, metricLabel: "Área (m²) / unidad" },
  { category: "Mampostería", name: "Ladrillo caravista (cara vista)", density: 1900, metricLabel: "Área (m²) / unidad" },
  { category: "Mampostería", name: "Ladrillo de campo (artesanal)", density: 1650, metricLabel: "Área (m²) / unidad" },
  { category: "Mampostería", name: "Bloque de hormigón con arcilla expandida", density: 1300, metricLabel: "Área (m²) / unidad" },
  { category: "Mampostería", name: "Piedra artificial reconstituida para muro", density: 2200, metricLabel: "Área (m²) / unidad" },
  { category: "Piedra natural", name: "Granito", density: 2700, metricLabel: "Volumen (m³) / Área (m²)" },
  { category: "Piedra natural", name: "Mármol", density: 2700, metricLabel: "Volumen (m³) / Área (m²)" },
  { category: "Piedra natural", name: "Caliza", density: 2400, metricLabel: "Volumen (m³) / Área (m²)" },
  { category: "Piedra natural", name: "Arenisca", density: 2200, metricLabel: "Volumen (m³) / Área (m²)" },
  { category: "Piedra natural", name: "Pizarra (slate)", density: 2750, metricLabel: "Área (m²)" },
  { category: "Piedra natural", name: "Basalto", density: 2900, metricLabel: "Volumen (m³)" },
  { category: "Piedra natural", name: "Cuarcita", density: 2650, metricLabel: "Volumen (m³) / Área (m²)" },
  { category: "Piedra natural", name: "Travertino", density: 2400, metricLabel: "Área (m²)" },
  { category: "Piedra natural", name: "Ónix", density: 2700, metricLabel: "Área (m²)" },
  { category: "Piedra natural", name: "Esteatita / piedra jabón (soapstone)", density: 2900, metricLabel: "Volumen (m³)" },
  { category: "Piedra natural", name: "Piedra laja (flagstone)", density: 2400, metricLabel: "Área (m²)" },
  { category: "Piedra natural", name: "Adoquín de piedra (cobblestone)", density: 2600, metricLabel: "Área (m²) / unidad" },
  { category: "Piedra natural", name: "Piedra de río (canto rodado)", density: 2600, metricLabel: "Volumen (m³)" },
  { category: "Piedra natural", name: "Piedra para gaviones", density: 2600, metricLabel: "Volumen (m³)" },
  { category: "Piedra natural", name: "Andesita", density: 2600, metricLabel: "Volumen (m³) / Área (m²)" },
  { category: "Piedra natural", name: "Toba volcánica", density: 1400, metricLabel: "Volumen (m³) / Área (m²)" },
  { category: "Piedra natural", name: "Sillar (piedra volcánica de Arequipa)", density: 1450, metricLabel: "Volumen (m³) / Área (m²)" },
  { category: "Piedra natural", name: "Piedra pómez", density: 900, metricLabel: "Volumen (m³)" },
  { category: "Piedra natural", name: "Dolomita", density: 2800, metricLabel: "Volumen (m³)" },
  { category: "Piedra natural", name: "Arenisca roja", density: 2100, metricLabel: "Volumen (m³) / Área (m²)" },
  { category: "Piedra natural", name: "Grauvaca", density: 2650, metricLabel: "Volumen (m³)" },
  { category: "Piedra natural", name: "Serpentinita", density: 2600, metricLabel: "Área (m²)" },
  { category: "Piedra natural", name: "Piedra laja negra", density: 2500, metricLabel: "Área (m²)" },
  { category: "Piedra natural", name: "Marmolina (mármol triturado decorativo)", density: 1500, metricLabel: "Volumen (m³)" },
  { category: "Piedra natural", name: "Piedra volcánica porosa (para jardín)", density: 1300, metricLabel: "Volumen (m³)" },
  { category: "Piedra natural", name: "Piedra caliza travertinada", density: 2350, metricLabel: "Área (m²)" },
  { category: "Piedra natural", name: "Gneis (para revestimiento)", density: 2700, metricLabel: "Área (m²)" },
  { category: "Piedra natural", name: "Piedra bola (canto grande de río)", density: 2600, metricLabel: "Volumen (m³)" },
  { category: "Piedra natural", name: "Piedra chancada 3/4\"", density: 1900, metricLabel: "Volumen (m³)" },
  { category: "Piedra natural", name: "Piedra Huamanga (alabastro peruano)", density: 2300, metricLabel: "Área (m²)" },
  { category: "Piedra natural", name: "Piedra berroqueña (granito de cantera)", density: 2650, metricLabel: "Volumen (m³)" },
  { category: "Piedra natural", name: "Cuarzo compacto (para encimeras)", density: 2650, metricLabel: "Área (m²)" },
  { category: "Piedra natural", name: "Basalto columnar (revestimiento)", density: 2900, metricLabel: "Área (m²)" },
  { category: "Piedra natural", name: "Piedra caliza coquina", density: 1900, metricLabel: "Volumen (m³)" },
  { category: "Vidrio", name: "Vidrio float (ventanas)", density: 2500, metricLabel: "Área (m²)" },
  { category: "Vidrio", name: "Vidrio templado", density: 2500, metricLabel: "Área (m²)" },
  { category: "Vidrio", name: "Vidrio laminado", density: 2500, metricLabel: "Área (m²)" },
  { category: "Vidrio", name: "Vidrio de control solar (low-E)", density: 2500, metricLabel: "Área (m²)" },
  { category: "Vidrio", name: "Vidrio armado (wired glass)", density: 2500, metricLabel: "Área (m²)" },
  { category: "Vidrio", name: "Vidrio tintado", density: 2500, metricLabel: "Área (m²)" },
  { category: "Vidrio", name: "Vidrio esmerilado (frosted)", density: 2500, metricLabel: "Área (m²)" },
  { category: "Vidrio", name: "Espejo (vidrio espejado)", density: 2500, metricLabel: "Área (m²)" },
  { category: "Vidrio", name: "Vidrio curvo (curvado en caliente)", density: 2500, metricLabel: "Área (m²)" },
  { category: "Vidrio", name: "Vidrio serigrafiado (fritado)", density: 2500, metricLabel: "Área (m²)" },
  { category: "Vidrio", name: "Vidrio fotovoltaico (BIPV)", density: 2600, metricLabel: "Área (m²)" },
  { category: "Vidrio", name: "Vidrio antibalas (multilaminado)", density: 2600, metricLabel: "Área (m²)" },
  { category: "Vidrio", name: "Vidrio acústico laminado", density: 2500, metricLabel: "Área (m²)" },
  { category: "Vidrio", name: "Vidrio autolimpiante", density: 2500, metricLabel: "Área (m²)" },
  { category: "Vidrio", name: "Vidrio decorativo texturado", density: 2500, metricLabel: "Área (m²)" },
  { category: "Vidrio", name: "Vidrio de seguridad estratificado", density: 2500, metricLabel: "Área (m²)" },
  { category: "Aislamiento", name: "Lana mineral (roca)", density: 100, metricLabel: "Área (m²) / Volumen (m³)" },
  { category: "Aislamiento", name: "Lana de vidrio (fibra de vidrio)", density: 16, metricLabel: "Área (m²) / Volumen (m³)" },
  { category: "Aislamiento", name: "Poliestireno expandido (EPS)", density: 20, metricLabel: "Área (m²) / Volumen (m³)" },
  { category: "Aislamiento", name: "Poliestireno extruido (XPS)", density: 35, metricLabel: "Área (m²) / Volumen (m³)" },
  { category: "Aislamiento", name: "Poliuretano expandido (PUR)", density: 30, metricLabel: "Área (m²) / Volumen (m³)" },
  { category: "Aislamiento", name: "Corcho aglomerado", density: 120, metricLabel: "Área (m²) / Volumen (m³)" },
  { category: "Aislamiento", name: "Celulosa insuflada", density: 45, metricLabel: "Volumen (m³)" },
  { category: "Aislamiento", name: "Perlita expandida", density: 100, metricLabel: "Volumen (m³)" },
  { category: "Aislamiento", name: "Vermiculita expandida", density: 100, metricLabel: "Volumen (m³)" },
  { category: "Aislamiento", name: "Aerogel (panel de aislamiento)", density: 150, metricLabel: "Área (m²)" },
  { category: "Aislamiento", name: "Espuma rígida de poliisocianurato (PIR)", density: 32, metricLabel: "Área (m²) / Volumen (m³)" },
  { category: "Aislamiento", name: "Aislamiento de cáñamo", density: 40, metricLabel: "Volumen (m³)" },
  { category: "Aislamiento", name: "Aislamiento de lana de oveja", density: 25, metricLabel: "Volumen (m³)" },
  { category: "Aislamiento", name: "Aislamiento de algodón reciclado (denim)", density: 50, metricLabel: "Volumen (m³)" },
  { category: "Aislamiento", name: "Panel de fibra de madera para aislamiento", density: 160, metricLabel: "Área (m²)" },
  { category: "Aislamiento", name: "Panel de vacío (VIP - vacuum insulated panel)", density: 200, metricLabel: "Área (m²)" },
  { category: "Aislamiento", name: "Espuma fenólica", density: 45, metricLabel: "Área (m²) / Volumen (m³)" },
  { category: "Aislamiento", name: "Lana de roca proyectada", density: 100, metricLabel: "Área (m²)" },
  { category: "Aislamiento", name: "Aislamiento reflectivo multicapa (foil)", density: 50, metricLabel: "Área (m²)" },
  { category: "Aislamiento", name: "Espuma de poliuretano proyectada", density: 35, metricLabel: "Área (m²)" },
  { category: "Aislamiento", name: "Aislamiento de fibra de poliéster reciclado", density: 30, metricLabel: "Volumen (m³)" },
  { category: "Aislamiento", name: "Manta térmica de fibra cerámica", density: 130, metricLabel: "Área (m²)" },
  { category: "Aislamiento", name: "Corcho expandido (para fachada)", density: 110, metricLabel: "Área (m²)" },
  { category: "Aislamiento", name: "Placa de silicato de calcio (aislante térmico)", density: 250, metricLabel: "Área (m²)" },
  { category: "Aislamiento", name: "Arcilla expandida a granel (aislamiento)", density: 350, metricLabel: "Volumen (m³)" },
  { category: "Aislamiento", name: "Espuma de melamina acústica", density: 9, metricLabel: "Área (m²)" },
  { category: "Aislamiento", name: "Aislamiento de fibra de yute", density: 40, metricLabel: "Volumen (m³)" },
  { category: "Aislamiento", name: "Panel de fibra de coco (aislante)", density: 90, metricLabel: "Área (m²)" },
  { category: "Yeso y placas", name: "Placa de yeso (drywall) estándar", density: 750, metricLabel: "Área (m²)" },
  { category: "Yeso y placas", name: "Placa de yeso resistente a la humedad", density: 800, metricLabel: "Área (m²)" },
  { category: "Yeso y placas", name: "Yeso (mortero de revoque)", density: 1200, metricLabel: "Área (m²) / Volumen (m³)" },
  { category: "Yeso y placas", name: "Fibrocemento (placa)", density: 1500, metricLabel: "Área (m²)" },
  { category: "Yeso y placas", name: "Placa de cemento (cement board)", density: 1200, metricLabel: "Área (m²)" },
  { category: "Yeso y placas", name: "Placa de óxido de magnesio (MgO)", density: 1000, metricLabel: "Área (m²)" },
  { category: "Yeso y placas", name: "Panel acústico de yeso perforado", density: 700, metricLabel: "Área (m²)" },
  { category: "Yeso y placas", name: "Panel de yeso reforzado con fibra de vidrio (GRG)", density: 1000, metricLabel: "Área (m²)" },
  { category: "Yeso y placas", name: "Placa de yeso resistente al fuego (tipo X)", density: 850, metricLabel: "Área (m²)" },
  { category: "Yeso y placas", name: "Placa de yeso flexible curvable", density: 900, metricLabel: "Área (m²)" },
  { category: "Yeso y placas", name: "Panel de yeso con núcleo de vermiculita", density: 950, metricLabel: "Área (m²)" },
  { category: "Yeso y placas", name: "Placa de yeso acústica ranurada", density: 750, metricLabel: "Área (m²)" },
  { category: "Plásticos y polímeros", name: "PVC rígido", density: 1400, metricLabel: "Peso (kg) / Longitud (m)" },
  { category: "Plásticos y polímeros", name: "Policarbonato", density: 1200, metricLabel: "Área (m²)" },
  { category: "Plásticos y polímeros", name: "Acrílico (PMMA)", density: 1180, metricLabel: "Área (m²)" },
  { category: "Plásticos y polímeros", name: "Polietileno de alta densidad (HDPE)", density: 950, metricLabel: "Peso (kg)" },
  { category: "Plásticos y polímeros", name: "Fibra de vidrio reforzada (FRP)", density: 1800, metricLabel: "Área (m²)" },
  { category: "Plásticos y polímeros", name: "Caucho / EPDM (membrana)", density: 1200, metricLabel: "Área (m²)" },
  { category: "Plásticos y polímeros", name: "Fibra de carbono (compuesto estructural)", density: 1600, metricLabel: "Peso (kg)" },
  { category: "Plásticos y polímeros", name: "Polipropileno (PP)", density: 900, metricLabel: "Peso (kg)" },
  { category: "Plásticos y polímeros", name: "Poliestireno rígido (PS)", density: 1050, metricLabel: "Peso (kg)" },
  { category: "Plásticos y polímeros", name: "Nylon (poliamida)", density: 1140, metricLabel: "Peso (kg)" },
  { category: "Plásticos y polímeros", name: "Silicona (sellador / membrana)", density: 1200, metricLabel: "Longitud (m) / Área (m²)" },
  { category: "Plásticos y polímeros", name: "Resina epóxica", density: 1100, metricLabel: "Volumen (m³) / Peso (kg)" },
  { category: "Plásticos y polímeros", name: "ABS", density: 1050, metricLabel: "Peso (kg)" },
  { category: "Plásticos y polímeros", name: "PET", density: 1380, metricLabel: "Peso (kg)" },
  { category: "Plásticos y polímeros", name: "Kevlar (fibra aramida, compuesto)", density: 1440, metricLabel: "Peso (kg)" },
  { category: "Plásticos y polímeros", name: "Fibra de vidrio compuesto (GFRP)", density: 1900, metricLabel: "Peso (kg) / Área (m²)" },
  { category: "Plásticos y polímeros", name: "Poliuretano rígido estructural", density: 1200, metricLabel: "Peso (kg)" },
  { category: "Plásticos y polímeros", name: "Polietileno reticulado (PEX)", density: 940, metricLabel: "Longitud (m)" },
  { category: "Plásticos y polímeros", name: "Polibutileno (PB)", density: 930, metricLabel: "Longitud (m)" },
  { category: "Plásticos y polímeros", name: "Resina de poliéster", density: 1200, metricLabel: "Volumen (m³) / Peso (kg)" },
  { category: "Plásticos y polímeros", name: "Silicona estructural (fachada)", density: 1300, metricLabel: "Longitud (m)" },
  { category: "Plásticos y polímeros", name: "PTFE sólido (teflón)", density: 2200, metricLabel: "Peso (kg)" },
  { category: "Plásticos y polímeros", name: "Nylon reforzado con fibra de vidrio", density: 1350, metricLabel: "Peso (kg)" },
  { category: "Plásticos y polímeros", name: "Policarbonato alveolar", density: 1200, metricLabel: "Área (m²)" },
  { category: "Plásticos y polímeros", name: "Acrílico colado (vaciado)", density: 1190, metricLabel: "Área (m²)" },
  { category: "Plásticos y polímeros", name: "PVC flexible", density: 1300, metricLabel: "Área (m²)" },
  { category: "Plásticos y polímeros", name: "Caucho SBR", density: 1100, metricLabel: "Área (m²)" },
  { category: "Plásticos y polímeros", name: "Poliuretano termoplástico (TPU)", density: 1200, metricLabel: "Peso (kg)" },
  { category: "Plásticos y polímeros", name: "Polioximetileno (POM / Delrin)", density: 1410, metricLabel: "Peso (kg)" },
  { category: "Plásticos y polímeros", name: "PVDF (fluoruro de polivinilideno, recubrimientos)", density: 1780, metricLabel: "Área (m²)" },
  { category: "Plásticos y polímeros", name: "Melamina (laminado decorativo)", density: 1500, metricLabel: "Área (m²)" },
  { category: "Plásticos y polímeros", name: "Baquelita (resina fenólica)", density: 1350, metricLabel: "Peso (kg)" },
  { category: "Paneles y compuestos", name: "Panel compuesto de aluminio (ACP / Alucobond)", density: 1500, metricLabel: "Área (m²)" },
  { category: "Paneles y compuestos", name: "Panel sándwich con núcleo de EPS", density: 40, metricLabel: "Área (m²)" },
  { category: "Paneles y compuestos", name: "Panel sándwich con núcleo de poliuretano (PUR)", density: 45, metricLabel: "Área (m²)" },
  { category: "Paneles y compuestos", name: "Panel de fibrocemento para fachada", density: 1500, metricLabel: "Área (m²)" },
  { category: "Paneles y compuestos", name: "Panel de cobre compuesto", density: 3000, metricLabel: "Área (m²)" },
  { category: "Paneles y compuestos", name: "Panel de zinc-titanio compuesto", density: 2800, metricLabel: "Área (m²)" },
  { category: "Paneles y compuestos", name: "Panel de piedra compuesta (sobre panal de aluminio)", density: 1800, metricLabel: "Área (m²)" },
  { category: "Paneles y compuestos", name: "Panel termoacústico (metal + aislamiento)", density: 60, metricLabel: "Área (m²)" },
  { category: "Paneles y compuestos", name: "Panel de bambú compuesto", density: 700, metricLabel: "Área (m²)" },
  { category: "Paneles y compuestos", name: "Panel de corcho compuesto para fachada", density: 250, metricLabel: "Área (m²)" },
  { category: "Paneles y compuestos", name: "Panel de aluminio perforado (fachada)", density: 2700, metricLabel: "Área (m²)" },
  { category: "Paneles y compuestos", name: "Panel GRC (hormigón reforzado con fibra de vidrio)", density: 1900, metricLabel: "Área (m²)" },
  { category: "Paneles y compuestos", name: "Panel HPL (laminado de alta presión)", density: 1350, metricLabel: "Área (m²)" },
  { category: "Pisos y revestimientos", name: "Porcelanato", density: 2400, metricLabel: "Área (m²)" },
  { category: "Pisos y revestimientos", name: "Cerámica esmaltada", density: 2000, metricLabel: "Área (m²)" },
  { category: "Pisos y revestimientos", name: "Piso vinílico (LVT)", density: 1400, metricLabel: "Área (m²)" },
  { category: "Pisos y revestimientos", name: "Piso laminado", density: 800, metricLabel: "Área (m²)" },
  { category: "Pisos y revestimientos", name: "Alfombra (con base)", density: 400, metricLabel: "Área (m²)" },
  { category: "Pisos y revestimientos", name: "Terrazo", density: 2300, metricLabel: "Área (m²)" },
  { category: "Pisos y revestimientos", name: "Piso de caucho", density: 1200, metricLabel: "Área (m²)" },
  { category: "Pisos y revestimientos", name: "Piso de bambú", density: 700, metricLabel: "Área (m²)" },
  { category: "Pisos y revestimientos", name: "Piso de corcho", density: 500, metricLabel: "Área (m²)" },
  { category: "Pisos y revestimientos", name: "Madera de ingeniería (engineered wood)", density: 600, metricLabel: "Área (m²)" },
  { category: "Pisos y revestimientos", name: "Piso epóxico autonivelante", density: 1600, metricLabel: "Área (m²)" },
  { category: "Pisos y revestimientos", name: "Piso de ladrillo (brick flooring)", density: 1850, metricLabel: "Área (m²)" },
  { category: "Pisos y revestimientos", name: "Piso de granito pulido", density: 2700, metricLabel: "Área (m²)" },
  { category: "Pisos y revestimientos", name: "Piso de mármol pulido", density: 2700, metricLabel: "Área (m²)" },
  { category: "Pisos y revestimientos", name: "Adoquín peatonal de arcilla", density: 1900, metricLabel: "Área (m²) / unidad" },
  { category: "Pisos y revestimientos", name: "Losa podotáctil (señalización táctil)", density: 2000, metricLabel: "Área (m²) / unidad" },
  { category: "Pisos y revestimientos", name: "Pasto sintético", density: 1100, metricLabel: "Área (m²)" },
  { category: "Pisos y revestimientos", name: "Piso deportivo de caucho reciclado", density: 1000, metricLabel: "Área (m²)" },
  { category: "Pisos y revestimientos", name: "Piso de resina epóxica con cuarzo", density: 2000, metricLabel: "Área (m²)" },
  { category: "Pisos y revestimientos", name: "Piso de hormigón pulido", density: 2400, metricLabel: "Área (m²)" },
  { category: "Pisos y revestimientos", name: "Piso flotante SPC (vinílico rígido)", density: 1900, metricLabel: "Área (m²)" },
  { category: "Pisos y revestimientos", name: "Alfombra modular (losetas)", density: 500, metricLabel: "Área (m²)" },
  { category: "Pisos y revestimientos", name: "Moqueta de fibra sintética", density: 350, metricLabel: "Área (m²)" },
  { category: "Pisos y revestimientos", name: "Linóleo natural", density: 1200, metricLabel: "Área (m²)" },
  { category: "Pisos y revestimientos", name: "Piso de PVC homogéneo (uso industrial)", density: 1700, metricLabel: "Área (m²)" },
  { category: "Pisos y revestimientos", name: "Alfombra de yute natural", density: 300, metricLabel: "Área (m²)" },
  { category: "Pisos y revestimientos", name: "Piso de terracota", density: 1900, metricLabel: "Área (m²)" },
  { category: "Techos y membranas", name: "Teja de arcilla", density: 1900, metricLabel: "Área (m²) / unidad" },
  { category: "Techos y membranas", name: "Teja de concreto", density: 2000, metricLabel: "Área (m²) / unidad" },
  { category: "Techos y membranas", name: "Teja asfáltica", density: 1100, metricLabel: "Área (m²)" },
  { category: "Techos y membranas", name: "Membrana asfáltica impermeabilizante", density: 1100, metricLabel: "Área (m²)" },
  { category: "Techos y membranas", name: "Chapa de acero para techo (steel deck)", density: 7850, metricLabel: "Área (m²) / Peso (kg)" },
  { category: "Techos y membranas", name: "Chapa de aluminio para techo", density: 2700, metricLabel: "Área (m²) / Peso (kg)" },
  { category: "Techos y membranas", name: "Chapa de zinc para techo", density: 7140, metricLabel: "Área (m²) / Peso (kg)" },
  { category: "Techos y membranas", name: "Membrana TPO", density: 1300, metricLabel: "Área (m²)" },
  { category: "Techos y membranas", name: "Membrana de PVC para techos", density: 1300, metricLabel: "Área (m²)" },
  { category: "Techos y membranas", name: "Sustrato para techo verde", density: 900, metricLabel: "Volumen (m³) / Área (m²)" },
  { category: "Techos y membranas", name: "Paja (techo de paja / thatch)", density: 250, metricLabel: "Área (m²)" },
  { category: "Techos y membranas", name: "Teja solar fotovoltaica", density: 2600, metricLabel: "Área (m²) / unidad" },
  { category: "Techos y membranas", name: "Canaleta de PVC para desagüe pluvial", density: 1400, metricLabel: "Longitud (m)" },
  { category: "Techos y membranas", name: "Canaleta de aluminio para desagüe pluvial", density: 2700, metricLabel: "Longitud (m)" },
  { category: "Techos y membranas", name: "Teja de bambú", density: 700, metricLabel: "Área (m²) / unidad" },
  { category: "Techos y membranas", name: "Teja ecológica (fibra reciclada)", density: 1000, metricLabel: "Área (m²) / unidad" },
  { category: "Techos y membranas", name: "Techo verde extensivo (sistema completo)", density: 150, metricLabel: "Área (m²)" },
  { category: "Techos y membranas", name: "Techo de policarbonato alveolar", density: 1200, metricLabel: "Área (m²)" },
  { category: "Membranas textiles", name: "Membrana PTFE recubierto de fibra de vidrio", density: 1500, metricLabel: "Área (m²) — se cotiza por peso areal (g/m²)" },
  { category: "Membranas textiles", name: "Película de ETFE", density: 1750, metricLabel: "Área (m²) — se cotiza por peso areal (g/m²)" },
  { category: "Membranas textiles", name: "Lona de PVC para estructuras tensadas", density: 1300, metricLabel: "Área (m²) — se cotiza por peso areal (g/m²)" },
  { category: "Membranas textiles", name: "Malla de sombra (raschel)", density: 900, metricLabel: "Área (m²) — se cotiza por peso areal (g/m²)" },
  { category: "Membranas textiles", name: "Tensoestructura de poliéster con PVC", density: 1300, metricLabel: "Área (m²) — se cotiza por peso areal (g/m²)" },
  { category: "Membranas textiles", name: "Malla mosquitera (fibra de vidrio o poliéster)", density: 900, metricLabel: "Área (m²)" },
  { category: "Suelos y áridos", name: "Tierra suelta (relleno)", density: 1500, metricLabel: "Volumen (m³)" },
  { category: "Suelos y áridos", name: "Tierra compactada", density: 1900, metricLabel: "Volumen (m³)" },
  { category: "Suelos y áridos", name: "Arena", density: 1600, metricLabel: "Volumen (m³)" },
  { category: "Suelos y áridos", name: "Grava", density: 1800, metricLabel: "Volumen (m³)" },
  { category: "Suelos y áridos", name: "Piedra triturada (base/subbase)", density: 2000, metricLabel: "Volumen (m³)" },
  { category: "Suelos y áridos", name: "Asfalto (ligante puro)", density: 1000, metricLabel: "Volumen (m³) / Peso (kg)" },
  { category: "Suelos y áridos", name: "Tierra vegetal (topsoil)", density: 1300, metricLabel: "Volumen (m³)" },
  { category: "Suelos y áridos", name: "Arcilla (suelo arcilloso)", density: 1800, metricLabel: "Volumen (m³)" },
  { category: "Suelos y áridos", name: "Limo (suelo limoso)", density: 1700, metricLabel: "Volumen (m³)" },
  { category: "Suelos y áridos", name: "Enrocado / rip-rap", density: 2600, metricLabel: "Volumen (m³)" },
  { category: "Suelos y áridos", name: "Relleno de cantera (rock fill)", density: 2200, metricLabel: "Volumen (m³)" },
  { category: "Suelos y áridos", name: "Grava de río (canto rodado suelto)", density: 1700, metricLabel: "Volumen (m³)" },
  { category: "Suelos y áridos", name: "Balasto ferroviario", density: 1800, metricLabel: "Volumen (m³)" },
  { category: "Suelos y áridos", name: "Arena de fundición", density: 1500, metricLabel: "Volumen (m³)" },
  { category: "Suelos y áridos", name: "Arena sílice", density: 1700, metricLabel: "Volumen (m³)" },
  { category: "Suelos y áridos", name: "Grava calcárea", density: 1700, metricLabel: "Volumen (m³)" },
  { category: "Suelos y áridos", name: "Hormigón reciclado triturado", density: 2200, metricLabel: "Volumen (m³)" },
  { category: "Suelos y áridos", name: "Escombro reciclado (relleno)", density: 1800, metricLabel: "Volumen (m³)" },
  { category: "Suelos y áridos", name: "Tierra de diatomeas", density: 500, metricLabel: "Volumen (m³)" },
  { category: "Suelos y áridos", name: "Bentonita", density: 800, metricLabel: "Volumen (m³)" },
  { category: "Suelos y áridos", name: "Arcilla expandida (LECA) a granel", density: 350, metricLabel: "Volumen (m³)" },
  { category: "Suelos y áridos", name: "Turba (suelo orgánico)", density: 400, metricLabel: "Volumen (m³)" },
  { category: "Suelos y áridos", name: "Marga (suelo franco)", density: 1600, metricLabel: "Volumen (m³)" },
  { category: "Suelos y áridos", name: "Caliche (suelo cementado natural)", density: 1900, metricLabel: "Volumen (m³)" },
  { category: "Tuberías y conducciones", name: "PVC sanitario (tubería)", density: 1400, metricLabel: "Longitud (m)" },
  { category: "Tuberías y conducciones", name: "PVC presión (tubería de agua)", density: 1400, metricLabel: "Longitud (m)" },
  { category: "Tuberías y conducciones", name: "PEX (tubería de agua caliente/fría)", density: 940, metricLabel: "Longitud (m)" },
  { category: "Tuberías y conducciones", name: "CPVC (tubería agua caliente)", density: 1550, metricLabel: "Longitud (m)" },
  { category: "Tuberías y conducciones", name: "Polietileno HDPE para agua/gas", density: 950, metricLabel: "Longitud (m)" },
  { category: "Tuberías y conducciones", name: "Polipropileno PP-R (tubería)", density: 900, metricLabel: "Longitud (m)" },
  { category: "Tuberías y conducciones", name: "Cobre para tubería de agua", density: 8960, metricLabel: "Longitud (m)" },
  { category: "Tuberías y conducciones", name: "Hierro fundido dúctil para tubería", density: 7100, metricLabel: "Longitud (m) / Peso (kg)" },
  { category: "Tuberías y conducciones", name: "Acero al carbono para tubería", density: 7850, metricLabel: "Longitud (m) / Peso (kg)" },
  { category: "Tuberías y conducciones", name: "Acero galvanizado para tubería", density: 7850, metricLabel: "Longitud (m) / Peso (kg)" },
  { category: "Tuberías y conducciones", name: "Concreto para tubería de alcantarillado", density: 2400, metricLabel: "Longitud (m) / unidad" },
  { category: "Tuberías y conducciones", name: "Fibrocemento para tubería", density: 1500, metricLabel: "Longitud (m)" },
  { category: "Tuberías y conducciones", name: "PRFV (poliéster reforzado con fibra de vidrio) para tubería", density: 1800, metricLabel: "Longitud (m)" },
  { category: "Tuberías y conducciones", name: "Gres cerámico para alcantarillado", density: 2000, metricLabel: "Longitud (m) / unidad" },
  { category: "Tuberías y conducciones", name: "Polietileno corrugado para drenaje", density: 950, metricLabel: "Longitud (m)" },
  { category: "Geosintéticos", name: "Geotextil no tejido", density: 200, metricLabel: "Área (m²) — se cotiza por peso areal (g/m²)" },
  { category: "Geosintéticos", name: "Geotextil tejido", density: 250, metricLabel: "Área (m²) — se cotiza por peso areal (g/m²)" },
  { category: "Geosintéticos", name: "Geomembrana de HDPE", density: 950, metricLabel: "Área (m²)" },
  { category: "Geosintéticos", name: "Geomembrana de PVC", density: 1300, metricLabel: "Área (m²)" },
  { category: "Geosintéticos", name: "Geomalla uniaxial (refuerzo de suelos)", density: 950, metricLabel: "Área (m²)" },
  { category: "Geosintéticos", name: "Geomalla biaxial (refuerzo de suelos)", density: 950, metricLabel: "Área (m²)" },
  { category: "Geosintéticos", name: "Geocelda (confinamiento celular)", density: 950, metricLabel: "Área (m²)" },
  { category: "Geosintéticos", name: "Geodrén (drenaje planar)", density: 950, metricLabel: "Área (m²)" },
  { category: "Geosintéticos", name: "Georred (control de erosión)", density: 900, metricLabel: "Área (m²)" },
  { category: "Geosintéticos", name: "Manta antierosión biodegradable", density: 300, metricLabel: "Área (m²)" },
  { category: "Adhesivos y selladores", name: "Sellador de silicona", density: 1200, metricLabel: "Longitud (m)" },
  { category: "Adhesivos y selladores", name: "Sellador de poliuretano", density: 1300, metricLabel: "Longitud (m)" },
  { category: "Adhesivos y selladores", name: "Sellador acrílico", density: 1500, metricLabel: "Longitud (m)" },
  { category: "Adhesivos y selladores", name: "Adhesivo epóxico estructural", density: 1600, metricLabel: "Volumen (m³)" },
  { category: "Adhesivos y selladores", name: "Adhesivo de contacto (neopreno)", density: 900, metricLabel: "Área (m²)" },
  { category: "Adhesivos y selladores", name: "Cinta asfáltica autoadherente", density: 1100, metricLabel: "Área (m²)" },
  { category: "Adhesivos y selladores", name: "Mortero adhesivo para cerámica (cemento cola)", density: 1500, metricLabel: "Área (m²)" },
  { category: "Adhesivos y selladores", name: "Masilla acrílica para juntas", density: 1600, metricLabel: "Longitud (m)" },
  { category: "Adhesivos y selladores", name: "Sellador de poliazufre (polysulfide)", density: 1500, metricLabel: "Longitud (m)" },
  { category: "Adhesivos y selladores", name: "Espuma de poliuretano expansiva para sellado", density: 25, metricLabel: "Volumen (m³)" },
  { category: "Adhesivos y selladores", name: "Adhesivo de poliuretano para madera estructural", density: 1100, metricLabel: "Volumen (m³)" },
  { category: "Adhesivos y selladores", name: "Cinta doble contacto para vidrio estructural", density: 1000, metricLabel: "Longitud (m)" },
  { category: "Fachadas y revestimiento exterior", name: "Siding vinílico", density: 1400, metricLabel: "Área (m²)" },
  { category: "Fachadas y revestimiento exterior", name: "Siding de fibrocemento", density: 1500, metricLabel: "Área (m²)" },
  { category: "Fachadas y revestimiento exterior", name: "EIFS (sistema de aislamiento y acabado exterior)", density: 300, metricLabel: "Área (m²)" },
  { category: "Fachadas y revestimiento exterior", name: "Ladrillo de cara vista para fachada", density: 1900, metricLabel: "Área (m²) / unidad" },
  { category: "Fachadas y revestimiento exterior", name: "Piedra reconstituida para fachada", density: 2200, metricLabel: "Área (m²)" },
  { category: "Fachadas y revestimiento exterior", name: "Panel de zinc-titanio para fachada", density: 7200, metricLabel: "Área (m²)" },
  { category: "Fachadas y revestimiento exterior", name: "Panel de cobre para fachada", density: 8960, metricLabel: "Área (m²)" },
  { category: "Fachadas y revestimiento exterior", name: "Madera termotratada para fachada", density: 470, metricLabel: "Área (m²)" },
  { category: "Fachadas y revestimiento exterior", name: "Revestimiento de piedra laminada (delgada)", density: 2600, metricLabel: "Área (m²)" },
  { category: "Fachadas y revestimiento exterior", name: "Panel HPL para fachada ventilada", density: 1350, metricLabel: "Área (m²)" },
  { category: "Fachadas y revestimiento exterior", name: "Revestimiento cerámico para fachada ventilada", density: 2000, metricLabel: "Área (m²)" },
  { category: "Fachadas y revestimiento exterior", name: "Panel GRC para fachada", density: 1900, metricLabel: "Área (m²)" },
  { category: "Fachadas y revestimiento exterior", name: "Malla metálica expandida para fachada", density: 2700, metricLabel: "Área (m²)" },
  { category: "Fachadas y revestimiento exterior", name: "Panel de policarbonato para fachada", density: 1200, metricLabel: "Área (m²)" },
  { category: "Fachadas y revestimiento exterior", name: "Revestimiento de corcho para fachada", density: 250, metricLabel: "Área (m²)" },
  { category: "Fachadas y revestimiento exterior", name: "Panel de aluminio compuesto ignífugo (núcleo mineral)", density: 1800, metricLabel: "Área (m²)" },
  { category: "Fachadas y revestimiento exterior", name: "Lama de madera termotratada para parasol", density: 470, metricLabel: "Longitud (m)" },
  { category: "Fachadas y revestimiento exterior", name: "Celosía de aluminio para fachada", density: 2700, metricLabel: "Área (m²)" },
  { category: "Prefabricados de concreto", name: "Vigueta pretensada", density: 2400, metricLabel: "Longitud (m) / unidad" },
  { category: "Prefabricados de concreto", name: "Bovedilla de poliestireno", density: 25, metricLabel: "unidad" },
  { category: "Prefabricados de concreto", name: "Bovedilla cerámica", density: 1200, metricLabel: "unidad" },
  { category: "Prefabricados de concreto", name: "Panel prefabricado de hormigón (tilt-up)", density: 2400, metricLabel: "Área (m²)" },
  { category: "Prefabricados de concreto", name: "Losa alveolar pretensada", density: 1800, metricLabel: "Área (m²)" },
  { category: "Prefabricados de concreto", name: "Bloque prefabricado para muro de contención", density: 2300, metricLabel: "unidad" },
  { category: "Prefabricados de concreto", name: "Tubo de hormigón para alcantarillado", density: 2400, metricLabel: "Longitud (m) / unidad" },
  { category: "Prefabricados de concreto", name: "Poste de concreto pretensado", density: 2400, metricLabel: "unidad / Longitud (m)" },
  { category: "Prefabricados de concreto", name: "Traviesa de concreto para ferrocarril", density: 2400, metricLabel: "unidad" },
  { category: "Prefabricados de concreto", name: "Adoquín prefabricado de concreto (peatonal)", density: 2300, metricLabel: "Área (m²) / unidad" },
  { category: "Fibras de refuerzo", name: "Fibra de acero para concreto", density: 7850, metricLabel: "Peso (kg)" },
  { category: "Fibras de refuerzo", name: "Fibra de polipropileno para concreto", density: 910, metricLabel: "Peso (kg)" },
  { category: "Fibras de refuerzo", name: "Fibra de vidrio AR para concreto", density: 2680, metricLabel: "Peso (kg)" },
  { category: "Fibras de refuerzo", name: "Fibra de basalto para concreto", density: 2700, metricLabel: "Peso (kg)" },
  { category: "Fibras de refuerzo", name: "Laminado de fibra de carbono (FRP) para refuerzo", density: 1600, metricLabel: "Longitud (m) / Área (m²)" },
  { category: "Fibras de refuerzo", name: "Malla de fibra de vidrio para refuerzo de mortero", density: 1000, metricLabel: "Área (m²)" },
  { category: "Fibras de refuerzo", name: "Fibra de aramida para refuerzo estructural", density: 1440, metricLabel: "Peso (kg)" },
  { category: "Pisos técnicos y cielos rasos", name: "Panel de piso técnico con núcleo de sulfato de calcio", density: 1900, metricLabel: "Área (m²) / unidad" },
  { category: "Pisos técnicos y cielos rasos", name: "Panel de piso técnico con núcleo de acero", density: 7850, metricLabel: "Área (m²) / unidad" },
  { category: "Pisos técnicos y cielos rasos", name: "Baldosa de fibra mineral para cielo raso", density: 350, metricLabel: "Área (m²) / unidad" },
  { category: "Pisos técnicos y cielos rasos", name: "Baldosa metálica perforada para cielo raso", density: 2700, metricLabel: "Área (m²) / unidad" },
  { category: "Pisos técnicos y cielos rasos", name: "Baldosa de madera para cielo raso", density: 600, metricLabel: "Área (m²) / unidad" },
  { category: "Pisos técnicos y cielos rasos", name: "Perfil de aluminio para cielo raso suspendido", density: 2700, metricLabel: "Longitud (m)" },
  { category: "Pisos técnicos y cielos rasos", name: "Panel acústico de fieltro de poliéster", density: 200, metricLabel: "Área (m²)" },
  { category: "Pisos técnicos y cielos rasos", name: "Panel de lana de madera mineralizada", density: 500, metricLabel: "Área (m²)" },
  { category: "Pisos técnicos y cielos rasos", name: "Baldosa de PVC para cielo raso", density: 1400, metricLabel: "Área (m²) / unidad" },
  { category: "Paisajismo y exteriores", name: "Mantillo de corteza (mulch)", density: 250, metricLabel: "Volumen (m³)" },
  { category: "Paisajismo y exteriores", name: "Grava decorativa", density: 1700, metricLabel: "Volumen (m³)" },
  { category: "Paisajismo y exteriores", name: "Adoquín ecológico (con césped)", density: 2000, metricLabel: "Área (m²) / unidad" },
  { category: "Paisajismo y exteriores", name: "Pasto sintético para jardín", density: 1100, metricLabel: "Área (m²)" },
  { category: "Paisajismo y exteriores", name: "Arena para arenero infantil", density: 1500, metricLabel: "Volumen (m³)" },
  { category: "Paisajismo y exteriores", name: "Tierra de cultivo mejorada (sustrato)", density: 900, metricLabel: "Volumen (m³)" },
  { category: "Paisajismo y exteriores", name: "Corteza de pino decorativa", density: 250, metricLabel: "Volumen (m³)" },
  { category: "Paisajismo y exteriores", name: "Grava de río decorativa", density: 1600, metricLabel: "Volumen (m³)" },
  { category: "Paisajismo y exteriores", name: "Sustrato para muro verde", density: 700, metricLabel: "Volumen (m³)" },
  { category: "Paisajismo y exteriores", name: "Roca ornamental de jardín", density: 2600, metricLabel: "unidad" },
  { category: "Aceros e instalaciones", name: "Conduit eléctrico de acero (EMT)", density: 7850, metricLabel: "Longitud (m)" },
  { category: "Aceros e instalaciones", name: "Conduit eléctrico de PVC", density: 1400, metricLabel: "Longitud (m)" },
  { category: "Aceros e instalaciones", name: "Bandeja portacables de acero galvanizado", density: 7850, metricLabel: "Longitud (m)" },
  { category: "Aceros e instalaciones", name: "Tubo de andamio de acero", density: 7850, metricLabel: "Longitud (m)" },
  { category: "Aceros e instalaciones", name: "Placa de encofrado metálica", density: 7850, metricLabel: "Área (m²)" },
  { category: "Aceros e instalaciones", name: "Malla de gallinero galvanizada", density: 7140, metricLabel: "Área (m²)" },
  { category: "Aceros e instalaciones", name: "Malla de acero inoxidable para barandas", density: 8000, metricLabel: "Área (m²)" },
  { category: "Aceros e instalaciones", name: "Perfil de aluminio estructural para muro cortina", density: 2700, metricLabel: "Longitud (m)" },
  { category: "Pavimentación vial", name: "Mezcla asfáltica en caliente (MAC)", density: 2350, metricLabel: "Volumen (m³)" },
  { category: "Pavimentación vial", name: "Mezcla asfáltica en frío", density: 2200, metricLabel: "Volumen (m³)" },
  { category: "Pavimentación vial", name: "Base granular para vías", density: 2000, metricLabel: "Volumen (m³)" },
  { category: "Pavimentación vial", name: "Sub-base granular para vías", density: 1900, metricLabel: "Volumen (m³)" },
  { category: "Pavimentación vial", name: "Pavimento rígido de concreto (losa de vía)", density: 2400, metricLabel: "Volumen (m³)" },
  { category: "Pavimentación vial", name: "Slurry seal (sello asfáltico)", density: 2100, metricLabel: "Área (m²)" },
  { category: "Pavimentación vial", name: "Riego de liga asfáltico", density: 1000, metricLabel: "Área (m²)" },
  { category: "Pavimentación vial", name: "Micropavimento asfáltico", density: 2200, metricLabel: "Área (m²)" },
  { category: "Pavimentación vial", name: "Pavimento articulado (adoquín vehicular)", density: 2300, metricLabel: "Área (m²) / unidad" },
  { category: "Pavimentación vial", name: "Concreto asfáltico poroso (drenante)", density: 2100, metricLabel: "Volumen (m³)" },
  { category: "Materiales ignífugos y contrafuego", name: "Placa contrafuego de yeso reforzado", density: 900, metricLabel: "Área (m²)" },
  { category: "Materiales ignífugos y contrafuego", name: "Manta ignífuga de fibra cerámica", density: 130, metricLabel: "Área (m²)" },
  { category: "Materiales ignífugos y contrafuego", name: "Sellador cortafuego (firestop)", density: 1400, metricLabel: "Volumen (m³)" },
  { category: "Materiales ignífugos y contrafuego", name: "Mortero proyectado ignífugo (para estructuras)", density: 300, metricLabel: "Área (m²)" },
  { category: "Materiales ignífugos y contrafuego", name: "Panel de vermiculita contrafuego", density: 450, metricLabel: "Área (m²)" },
  { category: "Materiales ignífugos y contrafuego", name: "Lana de roca contrafuego", density: 100, metricLabel: "Área (m²)" },
  { category: "Materiales ignífugos y contrafuego", name: "Placa de silicato cálcico contrafuego", density: 870, metricLabel: "Área (m²)" },
  { category: "Materiales ignífugos y contrafuego", name: "Pintura intumescente (protección al fuego)", density: 1300, metricLabel: "Área (m²) — rendimiento por espesor de película" },
  { category: "Carpintería de puertas y ventanas", name: "Marco de PVC para ventanas", density: 1400, metricLabel: "Longitud (m) / unidad" },
  { category: "Carpintería de puertas y ventanas", name: "Marco de aluminio para ventanas", density: 2700, metricLabel: "Longitud (m) / unidad" },
  { category: "Carpintería de puertas y ventanas", name: "Marco de madera para ventanas", density: 550, metricLabel: "Longitud (m) / unidad" },
  { category: "Carpintería de puertas y ventanas", name: "Marco de acero para puertas cortafuego", density: 7850, metricLabel: "unidad" },
  { category: "Carpintería de puertas y ventanas", name: "Puerta de madera maciza", density: 650, metricLabel: "unidad" },
  { category: "Carpintería de puertas y ventanas", name: "Puerta de MDF enchapada", density: 750, metricLabel: "unidad" },
  { category: "Carpintería de puertas y ventanas", name: "Puerta metálica hueca", density: 7850, metricLabel: "unidad" },
  { category: "Carpintería de puertas y ventanas", name: "Puerta de vidrio templado con herrajes", density: 2500, metricLabel: "unidad" },
  { category: "Carpintería de puertas y ventanas", name: "Persiana de aluminio", density: 2700, metricLabel: "Área (m²)" },
  { category: "Carpintería de puertas y ventanas", name: "Persiana de madera", density: 550, metricLabel: "Área (m²)" },
];

async function main() {
  let created = 0;
  let updated = 0;
  for (const m of MATERIALS) {
    const result = await prisma.material.upsert({
      where: { category_name: { category: m.category, name: m.name } },
      create: m,
      update: { density: m.density, metricLabel: m.metricLabel },
    });
    if (result.createdAt.getTime() === result.updatedAt.getTime()) created++;
    else updated++;
  }
  console.log(`Materiales: ${created} nuevos, ${updated} actualizados (${MATERIALS.length} en total).`);
}

main()
  .catch((error) => {
    console.error('No se pudo completar la siembra de materiales:', error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await pool.end().catch(() => undefined);
  });
